---
title: "PS270 Final Project"
author: "Ellie DeCleene"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to...
 
- How do people's political beliefs change over time? Are people more likely to agree with Democrats when they're young and change their minds as they age? Or do people generally stay in the same party as they age, and the Republican share of the vote increases with age because previous non-voters begin to vote?

- How well do your parents' beliefs predict your beliefs?

- Is the number of different news sources consumed by a voter predictive of their political party?

## Project plan

How does the news consumed by Americans impact the strength of their political views? My hypothesis is that consuming a larger number of different news sources can increase acceptance of different viewpoints, while consuming an equivalent amount of information from only one news source leads to polarization. My explanatory variable would be the number of different news sources consumed by a voter; my outcome variable would be the response to questions that measure political polarization, such as "Could you be friends with someone of the opposite party?". I would want to control for the amount of news consumed (measured by time), because people with strong political beliefs likely consume more news overall, but I predict that getting news from multiple sources could lead to a more balanced worldview. My hypothesis would be supported if there is a positive correlation between the number of news sources consumed and the acceptance of disagreeing viewpoints; my hypothesis would be disproved if there is no relation or if there is a negative correlation.